[versions]
adsSdk = "3.0.8"
agp = "8.5.1"
appInstallSdk = "1.0.2"
kotlin = "1.9.21"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.1"
constraintlayout = "2.2.1"
koinAndroid = "3.1.5"
koinCore = "3.1.5"

firebaseBom = "33.7.0"
billing = "7.1.1"
playServicesAds = "22.5.0"
playServicesMeasurementApi = "22.1.2"

appUpdateKtx = "2.1.0"
rate-sdk-version = "2.0.2"

glideVersion = "4.16.0"
sdpVersion = "1.1.0"
segmentationVersion = "16.0.0-beta1"
exifinterface = "1.4.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koinCore" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-config = { module = "com.google.firebase:firebase-config" }
firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }

billing = { module = "com.android.billingclient:billing-ktx", version.ref = "billing" }
#Google Ad
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
play-services-measurement-api = { module = "com.google.android.gms:play-services-measurement-api", version.ref = "playServicesMeasurementApi" }
#Ecomobile Ad
ads-sdk = { module = "com.ecomobileapp:ads-sdk", version.ref = "adsSdk" }
app-install-sdk = { module = "com.ecomobileapp:app-install-sdk", version.ref = "appInstallSdk" }

glide = {  module = "com.github.bumptech.glide:glide", version.ref = "glideVersion" }
sdp = {  module = "com.intuit.sdp:sdp-android", version.ref = "sdpVersion" }

#Play console
rate-sdk = { module = "com.google.android.play:review-ktx", version.ref = "rate-sdk-version" }
app-update-ktx = { module = "com.google.android.play:app-update-ktx", version.ref = "appUpdateKtx" }

#Segmentation Subject
segmentation = { module = "com.google.android.gms:play-services-mlkit-subject-segmentation", version.ref = "segmentationVersion" }
androidx-exifinterface = { group = "androidx.exifinterface", name = "exifinterface", version.ref = "exifinterface" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }